# Generated by Django 4.0.2 on 2022-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_order_status_alter_usercreation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='Coupen_offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='Coupencode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeradress',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Return', 'Return')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
