# Generated by Django 4.0.2 on 2022-03-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='Coupencode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Canceled', 'Canceled')], default='Processing', max_length=100),
        ),
    ]
